### ISSUE TITLE
没太看明白跟另一个项目fakeApiTool-One-API的区别。

### ISSUE THREAD

**Issue by befantasy** [Yanyutin753/PandoraNext-TokensTool#1]
是不是一个是基于公开的Pandora proxy，一个是自部署proxy？

**Comment by Yanyutin753** [comment]
这个针对于pandoraNext，另一个正对于fakeOpen，如果之后fakeOpen关了话，就要用这个了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: befantasy ***@***.***&gt;
发送时间: 2023年11月18日 00:04
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 没太看明白跟另一个项目fakeApiTool-One-API的区别。 (Issue #1)





 
是不是一个是基于公开的Pandora proxy，一个是自部署proxy？
