### ISSUE TITLE
点了star，启动了但是看不到tokens

### ISSUE THREAD

**Issue by ysxk** [Yanyutin753/PandoraNext-TokensTool#12]
docker-compose.yaml是这样写的
version: '3'

services:
  tokensTool:
    image: yangclivia/tokenstool:latest
    container_name: tokensTool
    restart: always
    user: root
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /usr/local/bin/docker:/usr/bin/docker
      - /volume1/Docker/pandor/data:/volume1/Docker/pandor/data
    command: 
      - --loginUsername=siqwrqwrzczxcqrng
      - --loginPassword=asdqwraxczxgqwefasd
      - --deployWay=docker
      - --deployPosition=/volume1/Docker/pandor/data
     能正常启动，也能访问，但是没法重启pandora-next，也看不到tokens，/volume1/Docker/pandor/data下面放的是pandora-next的config.json和token的json文件
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/39526083/8c150d1d-5e90-4fa3-8d31-6f162ce09a37)
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/39526083/162ae715-9f88-4eea-8415-5e1d19a5f489)

**Comment by Yanyutin753** [comment]
肯定看不到啊 你都没添加

**Comment by Yanyutin753** [comment]
你的pandoranext的容器名叫啥

**Comment by ysxk** [comment]
> 肯定看不到啊你都没有添加

添加了也没有的

**Comment by Yanyutin753** [comment]
看你的报错

**Comment by ysxk** [comment]
> 你的潘多拉下一个容器名叫啥
提示添加失败 
pandora的下一个容器是linweiyuan大佬的gpt-api
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/39526083/82cb8160-e2b6-4871-9a21-d926839f8d8d)

**Comment by Yanyutin753** [comment]
/volume1/Docker/pandor/data这个路径不是你的绝对路径，我感觉

**Comment by Yanyutin753** [comment]
然后这个可能错了，导致你无法重启

**Comment by ysxk** [comment]
> 你的pandoranext的容器名叫啥
pengzhile-pandora-next-1
我用docker-compose启动的，如果不是绝对路径应该会报错吧？

**Comment by Yanyutin753** [comment]
这个得改 我的启动docker用的是PandoraNext

**Comment by Yanyutin753** [comment]
应该是，我映射也是从绝对路径映射到容器路径

**Comment by allonmymind** [comment]
> PandoraNext

我和楼主一样的问题，新增的token刷新后就消失了，重启暂停启动均不起作用，终端docker restart PandoraNext是没问题的。
version: '3'

services:
  tokensTool:
    image: yangclivia/tokenstool:latest
    container_name: tokensTool
    restart: always
    user: root
    ports:
      - "8182:8081"
    network_mode: host
    pid: host
    privileged: true
    volumes:
      - /app/pandora/data:/app/pandora/data
      - /usr/bin/docker:/usr/bin/docker
    command: 
      - --loginUsername=admin
      - --loginPassword=abcdefg
      - --deployWay=docker
      - --server.port=8182
      - --deployPosition=/app/pandora/data

**Comment by Yanyutin753** [comment]
> > PandoraNext
> 
> 
> 
> 我和楼主一样的问题，新增的token刷新后就消失了，重启暂停启动均不起作用，终端docker restart PandoraNext是没问题的。
> 
> version: '3'
> 
> 
> 
> services:
> 
>   tokensTool:
> 
>     image: yangclivia/tokenstool:latest
> 
>     container_name: tokensTool
> 
>     restart: always
> 
>     user: root
> 
>     ports:
> 
>       - "8182:8081"
> 
>     network_mode: host
> 
>     pid: host
> 
>     privileged: true
> 
>     volumes:
> 
>       - /app/pandora/data:/app/pandora/data
> 
>       - /usr/bin/docker:/usr/bin/docker
> 
>     command: 
> 
>       - --loginUsername=admin
> 
>       - --loginPassword=abcdefg
> 
>       - --deployWay=docker
> 
>       - --server.port=8182
> 
>       - --deployPosition=/app/pandora/data

如果终端没问题 那就是绝对路径错了

**Comment by Yanyutin753** [comment]
没有连上你们的路径

**Comment by Yanyutin753** [comment]
绝对路径不是你们docker里面的路径，是宿主机里的路径

**Comment by ysxk** [comment]
> 绝对路径不是你们docker里面的路径，是宿主机里的路径

我把docker里的路径和宿主机里的路径设置的一样的，都是/volume1..........

**Comment by Yanyutin753** [comment]
报错有连接到你们的那个路径里的值嘛

**Comment by ysxk** [comment]
> 报错有连接到你们的那个路径里的值嘛

![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/39526083/33dfaf15-90ab-46e3-9106-db398b5a3b8e)

**Comment by Yanyutin753** [comment]
你加我吧，我感觉他直接去你的路径创了一个tokens哈哈哈哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ysxk ***@***.***&gt;
发送时间: 2023年11月21日 15:47
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 点了star，启动了但是看不到tokens (Issue #12)





  
报错有连接到你们的那个路径里的值嘛

**Comment by ysxk** [comment]
> 你加我吧，我感觉他直接去你的路径创了一个tokens哈哈哈哈哈 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ysxk ***@***.***&gt; 发送时间: 2023年11月21日 15:47 收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt; 抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [Yanyutin753/PandoraNext-TokensTool] 点了star，启动了但是看不到tokens (Issue #12) 报错有连接到你们的那个路径里的值嘛 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

咋加你啊大佬

**Comment by Yanyutin753** [comment]
那个情侣项目下面有我二维码

**Comment by allonmymind** [comment]
> > > PandoraNext
> > 
> > 
> > 我和楼主一样的问题，新增的token刷新后就消失了，重启暂停启动均不起作用，终端docker restart PandoraNext是没问题的。
> > version: '3'
> > services:
> > tokensTool:
> > ```
> > image: yangclivia/tokenstool:latest
> > 
> > container_name: tokensTool
> > 
> > restart: always
> > 
> > user: root
> > 
> > ports:
> > 
> >   - "8182:8081"
> > 
> > network_mode: host
> > 
> > pid: host
> > 
> > privileged: true
> > 
> > volumes:
> > 
> >   - /app/pandora/data:/app/pandora/data
> > 
> >   - /usr/bin/docker:/usr/bin/docker
> > 
> > command: 
> > 
> >   - --loginUsername=admin
> > 
> >   - --loginPassword=abcdefg
> > 
> >   - --deployWay=docker
> > 
> >   - --server.port=8182
> > 
> >   - --deployPosition=/app/pandora/data
> > ```
> 
> 如果终端没问题 那就是绝对路径错了

我是使用的绝对路径，linux根目录下的/app目录。看我命令
root@jm:/# tree /app/pandora/
/app/pandora/
├── data
│   ├── config.json
│   └── tokens.json
├── docker-compose.yml
├── license.jwt
├── token_file.json
└── tokentool
    └── docker-compose.yml

2 directories, 6 files
root@jm:/#

**Comment by Yanyutin753** [comment]
已解决
