### ISSUE TITLE
请求支持热更新选项设置

### ISSUE THREAD

**Issue by SourceOnce** [Yanyutin753/PandoraNext-TokensTool#13]
最新版潘pandora 的config配置setup_password支持热更新，希望接口可以集成进去

**Comment by Yanyutin753** [comment]
现在不知道具体的接口，不知道加了该咋办

**Comment by SourceOnce** [comment]
可以看这个
https://fakeopen.org/PandoraNext/config.html

**Comment by Yanyutin753** [comment]
写好了，明天再发

**Comment by Yanyutin753** [comment]
但是有个问题 现在不支持登录密码热重载，密码不会报错，但是进不去，不知道为啥

**Comment by Yanyutin753** [comment]
搞定了，你可以拉取最新的看看
