### ISSUE TITLE
点击刷新后，填写的token值变为空

### ISSUE THREAD

**Issue by acocchat** [Yanyutin753/PandoraNext-TokensTool#16]
点击刷新后，填写的token值变为空

**Comment by Yanyutin753** [comment]
是这样的，因为fakeopen的接口关了，现在没有什么渠道可以更新，然后你刷新一下，又会显示的





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: acocchat ***@***.***&gt;
发送时间: 2023年11月22日 21:14
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 点击刷新后，填写的token值变为空 (Issue #16)





 
点击刷新后，填写的token值变为空

**Comment by acocchat** [comment]
我退出登录后又重新登录了一下就显示出来了

**Comment by Yanyutin753** [comment]
你刷新页面也会显示的，前端我还没改，我在等有啥方法可以登录验证
