### ISSUE TITLE
docker运行的，网页打不开

### ISSUE THREAD

**Issue by zoooqe** [Yanyutin753/PandoraNext-TokensTool#19]
不知道什么原因，我贴一下运行日志吧
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129477897/bab928ca-3bb8-47b5-8caa-959f8aa040dc)

**Comment by Solan999** [comment]
+1 师傅我也是

**Comment by Yanyutin753** [comment]
加群聊，可以直接一键安装，直接pandoranext和tokenstool





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Solan999 ***@***.***&gt;
发送时间: 2023年11月24日 18:07
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] docker运行的，网页打不开 (Issue #19)





 
+1 师傅我也是

**Comment by 124ffee** [comment]
把net改成bridge就行了host肯定运行不起来 sudo docker run -d   --restart=always   -u root   --name tokensTool   -p 5300:8081   --net=bridge   --pid=host   --privileged=true   -v /home/pi/Docker/PandoraNext/data:/data   yangclivia/tokenstool:latest   --deployWay=releases   --deployPosition=/home/pi/Docker/PandoraNext/data --hotReload=true --pandoara_Ip=127.0.0.1:5200

**Comment by Yanyutin753** [comment]
已改，这样可以吗

**Comment by zoooqe** [comment]
按照上面哥们发的改bridge能打开了，但是重载/验证和参数设置报错，我暂时先不折腾这个项目了

**Comment by 124ffee** [comment]
> 按照上面哥们发的改bridge能打开了，但是重载/验证和参数设置报错，我暂时先不折腾这个项目了

你原封不动的抄我的当然报错你按你自己的参数设置我只是告诉你作者的那个host错了要改成bridge其他按你自己的来，还有这个部署完了你还要在data目录下下载作者的那个参数包
