### ISSUE TITLE
可惜docker没装上。。。这个用不了

### ISSUE THREAD

**Issue by SmerckZak** [Yanyutin753/PandoraNext-TokensTool#2]
就是没搞明白JWT Token就是那串字符bearer后面那串还是我自己的session token。。。都试了。。。还是显示容器一直restarting，

**Comment by Yanyutin753** [comment]
别急，很快就出来，我已经写好多个版本的了，我现在再写改系统变量，等一会

**Comment by smerckzak** [comment]
> 别急，很快就出来，我已经写好多个版本的了，我现在再写改系统变量，等一会

jwt token 到底是哪个??

**Comment by Yanyutin753** [comment]
就是你在目录下面用了你拿到的指令，之后会在该目录出现一个liense.jwt的文件，你把里面的值复制就是那个

**Comment by smerckzak** [comment]
> 就是你在目录下面用了你拿到的指令，之后会在该目录出现一个liense.jwt的文件，你把里面的值复制就是那个

那是我的session token 但是我用这个安装也是一直显示restarting.不知道是不是还要别的环境?

**Comment by Yanyutin753** [comment]
你现在看看，都可以了手动的docker的都可以用了

**Comment by SmerckZak** [comment]
还是用了软件版，直接启动那种。刚安装还是不行
2023/11/18 07:52:12 Unable to verify the server's license: json: cannot unmarshal array into Go struct field License.aud of type string

**Comment by SmerckZak** [comment]
又看了一边issue的回答  docker装上了..我只装了docker  容器文件都在container里面,至于config token文件在哪倒不知道了

**Comment by Yanyutin753** [comment]
把jar包放在跟config.json同一位置就行，会主动生成tokens.json



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SmerckZak ***@***.***&gt;
发送时间: 2023年11月18日 17:25
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 可惜docker没装上。。。这个用不了 (Issue #2)





 
又看了一边issue的回答  docker装上了..我只装了docker  容器文件都在container里面,至于config token文件在哪倒不知道了
