### ISSUE TITLE
账号或密码错误！  账号或密码错误

### ISSUE THREAD

**Issue by kmtycjj-tyx** [Yanyutin753/PandoraNext-TokensTool#23]

**Comment by Yanyutin753** [comment]
提供错误日志

**Comment by Svelar** [comment]
> 提供错误日志

大佬，我也提示这个错误了，错误日志哪里导呢

**Comment by hqzh** [comment]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/26128706/73e582ba-9047-4549-8309-ff24acda0e81)

**Comment by runcode1** [comment]
2023-11-28 01:59:22.695  INFO 1673268 --- [nio-8081-exec-2] c.y.p.interceptor.LoginCheckInterceptor  : 登录操作, 放行...
空数组添加完成
config.json创建完成: /var/lib/docker/volumes/cd50a5597bcc7336370a766edc968aad5259f165c6dfe0b2c7598f70e8a15ab6/_data/config.json
org.json.JSONException: No value for timeout

可以访问但是也是账号密码错误

**Comment by runcode1** [comment]
可以了

**Comment by suhou** [comment]
<img width="1241" alt="image" src="https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/5761727/ed6e7358-da7c-47cc-ab9a-f97c0a23c170">
wo's我这是第一次登录这个页面，我输入了账号密码但是显示账号或密码错误

**Comment by Yanyutin753** [comment]
更新一下最新版本，然后可以是路径出现问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: suhou ***@***.***&gt;
发送时间: 2023年11月28日 12:00
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 账号或密码错误！  账号或密码错误 (Issue #23)





 image.png (view on web) wo's我这是第一次登录这个页面，我输入了账号密码但是显示账号或密码错误

**Comment by NPC-JIN** [comment]
同样的问题，首次部署后，使用默认的root及123456登录显示账号密码错误

**Comment by suhou** [comment]
还是不知道怎么解决

**Comment by suhou** [comment]
能教一下具体步骤吗，我不太熟悉

**Comment by NPC-JIN** [comment]
> 能教一下具体步骤吗，我不太熟悉

你是用docker部署吗，还是什么途径，总之先找到你当时部署Pandoranext的时候 data文件夹存放的位置，里面有你的config.json文件

**Comment by suhou** [comment]
我当时pandoranext手动部署，在文件夹里，然后pandoranext tokens tool是那个一键部署

**Comment by suhou** [comment]
![Uploading image.png…]()
这是我的docker界面

**Comment by NPC-JIN** [comment]
> 我当时pandoranext手动部署，在文件夹里，然后pandoranext tokens tool是那个一键部署

确定你是使用release的方式部署，那请找到data文件路径，填入readme文档中：docker-手动部署的代码，在命令行中运行，注意删除作者给出的提示性文字

**Comment by suhou** [comment]
<img width="717" alt="image" src="https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/5761727/bf1a4504-4fa1-4c9d-a7ce-d37d18a18296">
我找到的data文件在pandoraNext-0.0.1-SNAPSHOT文件夹很里面，把这个data填入这个readme？
<img width="723" alt="image" src="https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/5761727/86397d14-c5a1-4004-8672-357bea75d34a">

**Comment by suhou** [comment]
已经解决了，我刚在docker里找到修改文件的地方了
