### ISSUE TITLE
大佬 这个功能啥时实现呢

### ISSUE THREAD

**Issue by pdgxiaofei** [Yanyutin753/PandoraNext-TokensTool#29]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/37896719/41cb5515-11b4-4c5e-b89a-00da36b6d2ba)

**Comment by zzhhxx** [comment]
上游那个已经实现了，你在页面里面把刷新token地址改为自己的就行了：http://ip:port/api/auth/login
