### ISSUE TITLE
使用PandoraNext-TokensTool重启pandoraNext发现无法正常运行

### ISSUE THREAD

**Issue by fuchao2687** [Yanyutin753/PandoraNext-TokensTool#3]
感谢大佬开发的便捷工具。
我在备用vps上使用docker compose部署PandoraNext和PandoraNext-TokensTool，设置openai账号密码后能正常获取tokens，重新获取license.jwt文件并填入docker-compose.yml文件后，使用
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/34016090/de0fa385-7b08-4a1c-955d-a1b56843c633)
重启PandoraNext，发现并没有正常运行，原因可能是docker compose部署的方式进行重启并没有读取docker-compose.yml文件，需要手动删除再启动才能正常运行。纯小白不懂具体原理，这个重启功能可以再优化一下吗？
另外，请问PandoraNext-TokensTool是一个java程序吗？

**Comment by Yanyutin753** [comment]
java程序 奇怪 你试试更新一下 我现在试过docker和手动部署的，就差docker co那个了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 胡超 ***@***.***&gt;
发送时间: 2023年11月18日 15:24
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 使用PandoraNext-TokensTool重启pandoraNext发现无法正常运行 (Issue #3)





 
感谢大佬开发的便捷工具。
 我在备用vps上使用docker compose部署PandoraNext和PandoraNext-TokensTool，设置openai账号密码后能正常获取tokens，重新获取license.jwt文件并填入docker-compose.yml文件后，使用
 
 重启PandoraNext，发现并没有正常运行，原因可能是docker compose部署的方式进行重启并没有读取docker-compose.yml文件，需要手动删除再启动才能正常运行。纯小白不懂具体原理，这个重启功能可以再优化一下吗？
 另外，请问PandoraNext-TokensTool是一个java程序吗？

**Comment by fuchao2687** [comment]
竟然更新了，好快。
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/34016090/e3c708fa-5312-4788-aee0-dd071b832f62)
这个参数是指PandoraNext的部署方式吗？还是指PandoraNext-TokensTool的部署方式？

**Comment by Yanyutin753** [comment]
改后面代码用的，针对不同的部署方式，进行不同的启动关闭操作，你看看属于那种



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fc ***@***.***&gt;
发送时间: 2023年11月18日 15:42
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 使用PandoraNext-TokensTool重启pandoraNext发现无法正常运行 (Issue #3)





 
竟然更新了，好快。
 
 这个参数是指PandoraNext的部署方式吗？还是指PandoraNext-TokensTool的部署方式？

**Comment by fuchao2687** [comment]
大佬我试了一下还是一样，主要还是因为切换vps导致需要重新读取新的lincense，如果不换ip/vps的话应该不用管这个问题，再次感谢大佬的便捷工具。

**Comment by Yanyutin753** [comment]
你可以更改java程序使得每次使用执行jwt指令，拿到相应文件
