### ISSUE TITLE
【求助】关于添加账号和密码的问题

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#35]
只添加账号和密码一直提示：添加失败,检查你的账号密码是否正确或FakeOpen服务异常。

添加session后正常，但是无法刷新（刷新session_token失败,请尝重新刷新！），无法生成（生成access_token和share_token失败,请请确保填写token为session_token！）

不知道是不是我这边没有操作正确。谢谢啊

**Comment by taurusduan** [comment]
已经搞定了

**Comment by Yanyutin753** [comment]
更新4.4
解决所有问题

**Comment by Yanyutin753** [comment]
一键部署直接更新

**Comment by taurusduan** [comment]
> > 已经搞定了
> 
> 询问如何解决的，遇到同样的问题

我这边是双模式搞定，作者说更新。。。不知道现在是不是不用双模式也可以了

**Comment by taurusduan** [comment]
> 一键部署直接更新

大佬问一下，现在不需要使用two-PandoraNext就刷新token了吗？

**Comment by Yanyutin753** [comment]
对对对，直接一键部署就行
