### ISSUE TITLE
一键部署的，都更新到4.4，功能直接飞跃

### ISSUE THREAD

**Issue by Yanyutin753** [Yanyutin753/PandoraNext-TokensTool#36]

**Comment by xupeng19881010** [comment]
怎么老改部署方式，确实不方便，折腾。。。

**Comment by Yanyutin753** [comment]
直接一键部署，一键更新，还不方便嘛

**Comment by xupeng19881010** [comment]
添加失败,检查你的账号密码是否正确或FakeOpen服务异常

**Comment by xupeng19881010** [comment]
收到docker部署改怎么升级到4.4
tokensTool设置信息里的刷新token的网址改怎么填？

**Comment by Yanyutin753** [comment]
重拉镜像





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xupeng19881010 ***@***.***&gt;
发送时间: 2023年11月30日 21:37
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 一键部署的，都更新到4.4，功能直接飞跃 (Issue #36)





 
收到docker部署改怎么升级到4.4
 tokensTool设置信息里的刷新token的网址改怎么填？
