### ISSUE TITLE
更新4.4

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#37]
更新4.4
解决所有问题

_Originally posted by @Yanyutin753 in https://github.com/Yanyutin753/PandoraNext-TokensTool/issues/35#issuecomment-1833613142_
            
我这边是使用了双模式，现在不需要双模式了吗？

**Comment by Yanyutin753** [comment]
对 直接一键部署，保存之前的token，迁移

**Comment by XZ1314XZ** [comment]
@Yanyutin753  请求补充Dokerfile文件
