### ISSUE TITLE
更新4.5

### ISSUE THREAD

**Issue by Yanyutin753** [Yanyutin753/PandoraNext-TokensTool#38]
@所有人 更新4.5 
1.支持选定账号生成pool_token
2.支持热重载

热重载需要填写这个，这个获取方式f12PandoraNext,拿到cookies里的_Secure-next-auth.setup-password对应的值

**Comment by hqzh** [comment]
金光闪闪是随机从后台拿的使用这个项目的账号吗

**Comment by Yanyutin753** [comment]
查看是否分享
