### ISSUE TITLE
是否支持MS/Google登录以获取token

### ISSUE THREAD

**Issue by Qianmoxsn** [Yanyutin753/PandoraNext-TokensTool#4]
首先感谢大佬的贡献！！

我看目前tool只支持通过openai的账号和密码进行登录，而像其他的登录chat的方式比如（Google、ms、apple）现阶段是否是支持的？

是否有进一步适配的计划？

顺颂时祺！

**Comment by Yanyutin753** [comment]
难，得用插件

**Comment by Jesn** [comment]
> 难，得用插件

目前用的hotmail和 gmail注册，难搞。。。

**Comment by Yanyutin753** [comment]
注册 为啥没有账号密码，我都是找人买号的哈哈哈哈哈哈哈



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Darren ***@***.***&gt;
发送时间: 2023年11月21日 10:37
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 是否支持MS/Google登录以获取token (Issue #4)





  
难，得用插件
  
目前用的hotmail和 gmail注册，难搞。。。

**Comment by zazitufu** [comment]
前几天注册不需要手机……
