### ISSUE TITLE
【重要】安全问题，刻不容缓！

### ISSUE THREAD

**Issue by wozulong** [Yanyutin753/PandoraNext-TokensTool#40]
你好，我是PandoraNext项目作者。很感谢本项目对PandoraNext的支持与跟进。

但是从群友反馈来看，本项目中多处默认弱密码`123456`，特别是对于`site_password`参数来说，弱密码是**致命**的！
一个弱密码的`site_password`意味着你的 `config.json` `tokens.json` 甚至你的 `license_id` 都是直接暴露！而通常使用这个项目部署的人可能由于经验缺乏，根本不会去修改掉这个弱密码，导致极大的安全问题。且本项目搭建的默认账号密码也是 `root` 和 `123456`，同样非常危险。

以上反馈不是基于假设，是telegram群中有群友的搭建被盗用，而`site_password`就是默认的`123456`。

### 我建议不要内置 `site_password` 和 `proxy_api_prefix` 等参数。留空反而是最安全的，因为不会启用相关功能。除此之外，不管你默认的有多复杂，总有不去修改的人。

另外，提交代码请注意不要提交隐私：https://github.com/Yanyutin753/PandoraNext-TokensTool/blob/main/rearServer/tokens.json

**Comment by Yanyutin753** [comment]
参见吾皇，本臣马上修改！🥰🥰🥰

**Comment by devhaozi** [comment]
皇上费心了

**Comment by Yanyutin753** [comment]
在改了始皇🥺，谢谢提醒⭐️
