### ISSUE TITLE
登录绕过漏洞

### ISSUE THREAD

**Issue by renqabs** [Yanyutin753/PandoraNext-TokensTool#48]
jwt计算使用到的信息都是已知的，可伪造一个jwt，绕过用户名和密码，直接登录系统（不演示了，免得被人利用），建议使用密码或密码变种（MD5等）做为jwt计算的密钥，而非硬编码
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/913b322d-5075-4881-a443-586b9a0ad51b)
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/3cc06c9d-4a7c-4393-9f9c-5ece551bc9ad)

**Comment by hqzh** [comment]
看来上plus号使用还得再等等

**Comment by Yanyutin753** [comment]
小白还真没注意到这一点，我已修改，长知识了哈哈哈哈哈哈，感谢提醒，顺便再找找别的bug，让项目更好👍👍👍

**Comment by Yanyutin753** [comment]
更新到最新4.7.1,已更新硬编码，给大家造成了损失，对不起
