### ISSUE TITLE
第一次登录，用账户root，密码123456，报账户或密码错误。这是为什么？

### ISSUE THREAD

**Issue by AaronChen2** [Yanyutin753/PandoraNext-TokensTool#49]
docker部署后，第一次登录，用账户root，密码123456，报账户或密码错误。这是为什么？
<img width="433" alt="搜狗截图20231206201408" src="https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/60588863/f2694fb7-7dbb-445b-a6c7-a82d76b3dd14">

**Comment by jinwan0327** [comment]
同问

**Comment by Yanyutin753** [comment]
路径错了

**Comment by Yanyutin753** [comment]
不懂的话 可以加群 问问或者把报错日志打出来，这样看不懂的

**Comment by AaronChen2** [comment]
登录问题已经搞定，就是路径错了。请把我拉进群，谢谢～

**Comment by luojunjiess** [comment]
FJYpolo
837493986
求拉群

**Comment by alex-oos** [comment]
我都安装成功不了
