### ISSUE TITLE
这次被攻击，使得我心情很复杂

### ISSUE THREAD

**Issue by Yanyutin753** [Yanyutin753/PandoraNext-TokensTool#50]
最主要的原因还是因为自己没有处理好硬编码，还是安全知识没到位，看着群里的友友一个一个被修改密码，突然感觉蛮无助的，最有感觉的就是自己很对不起大家，感觉让大家被攻击了，辜负了大家的信任，有蛮多的号给泄漏出去了。对于大家的精神上的损失，和经济上的损失，我感到十分的抱歉，先跟大家说个对不起，没想到这种事情，会切切实实发生在我的身上，还是自己写的太少了，实力不足！也希望就此机会，能好好加强一下自己的安全意识！！！
大家如果还需要使用tokensTool来使用PandoraNext的API模式，请务必要更新到0.4.7.1这很重要，如果你只想用web的话，可以直接看PandoraNext的教程，始皇出了一个巨强的功能，只用账号密码就可以内置token啦！
希望以后自己不会再放这种错误，也希望大家之后也要多多留意！

**Comment by xiaosaaaa** [comment]
没事，继续努力。

**Comment by taurusduan** [comment]
大哥刚跟新好，请问一下pool_token有什么作用啊？

**Comment by Halecoder** [comment]
能发下微信群二维码吗

**Comment by Yanyutin753** [comment]
发不了 发了加不进去了，只能先加我 我把你拉进去



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Halecoder ***@***.***&gt;
发送时间: 2023年12月7日 21:34
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 这次被攻击，使得我心情很复杂 (Issue #50)





 
能发下微信群二维码吗

**Comment by Halecoder** [comment]
请问您微信多少

Clivia ***@***.***> 于2023年12月8日周五 09:18写道：

**Comment by liulisanwan** [comment]
方便加一下您的微信吗
