### ISSUE TITLE
点击生成或者刷新，操作失败

### ISSUE THREAD

**Issue by Qmymy** [Yanyutin753/PandoraNext-TokensTool#51]
在添加了账号后点击生成或者刷新都是操作失败，请问下这个是怎么回事？我用的是国内的VPS，是不是需要国外的vps才能刷新和生成呢？
![IMG_20231207_150431.jpg](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/e911f446-e94f-4460-b910-310adbafdf05)

![IMG_20231207_150409.jpg](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/60a5166f-24d9-4875-8beb-1ffcbec0fa54)

**Comment by Qmymy** [comment]
我填写的是session_token

**Comment by Yanyutin753** [comment]
内网的话 记得填写好刷新token的地址

**Comment by Qmymy** [comment]
我这里看懂了，我填写的本服务器的IP
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/323916e4-0fb7-4fa4-a38d-2f426e385f96)

我能确保填写的是session_token但是这里的JSON报错

生成share token返回未登录的信息
![qq_pic_merged_1701955671823](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/04793b14-8a99-4a29-b8ea-568469cff3b6)
就导致了还是出现以下情况：

![{JF@4G${5DNPI{ {60O6)19](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/087f52ca-619e-40bb-bfc5-3e9e1a929670)
![OF1{IK6PWK3X0 `9JE O81](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/06fe01be-ec38-46f9-880c-60e51cb026ef)

**Comment by Qmymy** [comment]
从前天的版本拉取到现在0.4.7的版本解决了之前的问题，能生成了其他token了，但是这里刷新session_token的话会出现
![~H_TFJ)04}JUC3E7Z 1__X9](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/d06ec3b6-a98c-4a24-b5db-62746f1b4bde)
显示太多的请求然后拒绝处理了，这应该不是我服务器的问题吧？然后就导致下图
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/129690756/d15aa728-6d95-4c35-bba8-3a596cb33d2f)

**Comment by Qmymy** [comment]
已经找到原因了，刷新token会导致https://dash.pandoranext.com/消耗额度，我限额了就不能使用刷新了，本问题已经解决感谢作者的优秀项目，有相关问题的可以参考下
