### ISSUE TITLE
+号添加tokens.json账户，表单数据未清除

### ISSUE THREAD

**Issue by woshiwufei** [Yanyutin753/PandoraNext-TokensTool#52]
通过右上角加号向tokens.json添加账户成功后，表单数据不会自动清除，（不关闭切换页面）继续点击加号会发现上一次的数据还在。

还有一个是之前版本发现的，没看到有人提issue，就是通过右上角更换pool_token时如果请求超时了loading效果不会自动消失（这个小问题不知道还存不存在，我目前没办法测试）

**Comment by Yanyutin753** [comment]
好 之后版本优化一下
