### ISSUE TITLE
反代之后api请求报错404。

### ISSUE THREAD

**Issue by taklele** [Yanyutin753/PandoraNext-TokensTool#54]
假设ip是1.1.1.1，域名是a.com。

没反代之前，访问：
1.1.1.1:8081                         正常
get  1.1.1.1:8081/pool_token?password=pass          正常
post   1.1.1.1:8081/pass/v1/chat/completions            正常

反代之后，访问
a.com                         正常
get  a.com/pool_token?password=pass          正常
post   a.com/pass/v1/chat/completions            404报错
----
为什么这里会是404报错呢？

**Comment by Yanyutin753** [comment]
8181

**Comment by Yanyutin753** [comment]
反代之后，如果没开端口，则在tool上修改你的proxy的url

**Comment by Yanyutin753** [comment]
v1用的是你的pandoraNext的服务，不是tokenstool

**Comment by taklele** [comment]
在反代中设置了location去代理8181端口，解决了，谢谢。
