### ISSUE TITLE
将通过这个网址请求登录信息：这里的IP没用使用配置的pandoara_Ip

### ISSUE THREAD

**Issue by zhao-wuyan** [Yanyutin753/PandoraNext-TokensTool#55]
这里的IP没用使用配置的pandoara_Ip，我没有开放到公网，一直获取我的公网IP。导致超时无法生成。这里应该也能自己配置自己部署的Pandora的IP才对吧。页面上或者配置文件哪里能配置一下

**Comment by Yanyutin753** [comment]
ip都可以 这里是重载的 刷新的去配置proxy的URL

**Comment by Yanyutin753** [comment]
都支持内网的哈
