### ISSUE TITLE
添加失败,检查你的账号密码是否正确或刷新token网址有误！

### ISSUE THREAD

**Issue by 757321061** [Yanyutin753/PandoraNext-TokensTool#56]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/49135603/ea20b2b5-c82c-4229-8df9-851b154717d8)

**Comment by hcj5206** [comment]
+1

**Comment by 757321061** [comment]
解决了，没啥问题，就是当时  验证licenseId  填成curl了，应该直接写License Id:
