### ISSUE TITLE
新版接口要怎么用？ 获取都是空

### ISSUE THREAD

**Issue by 757321061** [Yanyutin753/PandoraNext-TokensTool#58]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/49135603/11a4ab4c-6fd4-4456-89e8-8674dd94ee47)

**Comment by Yanyutin753** [comment]
tool开启接口之后就可以使用了呀，输入你要查的token名和获取token的密码，就可能拿到你tool里面存的数据
