### ISSUE TITLE
【bug】安装过程中报错，shell语法错误，定位了半天也没定位到问题，

### ISSUE THREAD

**Issue by alex-oos** [Yanyutin753/PandoraNext-TokensTool#60]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/46887064/79d1b403-52a4-411e-9544-4b7019d4b52c)

**Comment by Yanyutin753** [comment]
你的这个pandora目录是不是存在啊

**Comment by Yanyutin753** [comment]
删掉你git的文件夹
在git一下
