### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by superen7527** [Yanyutin753/PandoraNext-TokensTool#61]
看得出来刚接触docker，ui我也不提建议了，能用就好，哥们想法不错，继续加油。说几个建议

- 我看你都是覆盖源文件写入 这种属于破坏性行为，应该重新弄一个json记录你的数据而不是混用。或者都在新的一个key下。考虑到兼容迁移比较麻烦，建议修改后的json格式化 把你的数据排序放下面，区分比较明显。当然这是规范问题 和功能没关系。可以不用采纳。
- 希望可以添加修改test-1这种key名称 (目前需要手动改文件)
- 希望可以支持多listenid写法 用完了自动换一个新的 
- 可以添加share的分享账号邮箱
- 潘多拉在开启账号登录密码时如果开分享会出现启动异常报错。要做一个不共存开关检测。
- pool池建议拿出来放一个显眼的位置或者换一个菜单 而不是在重启潘多拉那个菜单里。同时希望支持复制按钮，手机试过复制有点难受
- 添加快捷跳转 在设置里写好host主机 然后可以跳转到以下界面：setup设置页 以及几个手动操作的非登录主页的页面(比如注册页) 潘多拉jwt用量页(或者通过api直接显示用量余额 你已经在白名单ip上了)
- **(可以做一个新的菜单就叫做快捷菜单之类的 里面放上面两条说的pool sharetoken相关和这些潘多拉客户端跳转页)**
- 添加的通知可以不用停留太久 特别是 感谢吾皇 这种，手机有点挡视野。我们心里都感谢吾皇。
- 希望可以和注册高度绑定 注册的账号自动添加记录 这个有点难 如果是监听容器也没必要 我也没想好什么模式
- 目前好像不支持潘多拉内置的账号密码模式(0额度消耗自动续期) 建议是只输入了账号密码的时候启用。而不是输入就提交拿Accesstoken，直接不检测账号密码的合理度用账号&密码写法，目前这样输入账号密码会扣额度，错误也扣，不如直接内置。
- 检测到没权限 或者容器名不对 就取消右上角的菜单 或者灰色 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
先说这些吧。看情况采纳
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by Yanyutin753** [comment]
好 考完试看看怎么优化一下

**Comment by YuWanTingbb** [comment]
目前修改修改test-1这种key名称 (目前需要手动改文件)，这个太过于麻烦，全都要改，这确实是开始埋下的坑，不应该用这个当主键的，希望可以支持多listenid写法 用完了自动换一个新的，这个不行的，绑定ip的，

**Comment by YuWanTingbb** [comment]
可以添加share的分享账号邮箱 ❌ 不太懂什么意思
潘多拉在开启账号登录密码时如果开分享会出现启动异常报错。要做一个不共存开关检测。✔
pool池建议拿出来放一个显眼的位置或者换一个菜单 而不是在重启潘多拉那个菜单里。同时希望支持复制按钮，手机试过复制有点难受 ✔
添加快捷跳转 在设置里写好host主机 然后可以跳转到以下界面：setup设置页 以及几个手动操作的非登录主页的页面(比如注册页) 潘多拉jwt用量页(或者通过api直接显示用量余额 你已经在白名单ip上了) ✔
(可以做一个新的菜单就叫做快捷菜单之类的 里面放上面两条说的pool sharetoken相关和这些潘多拉客户端跳转页) ❌ 手机端太小了
添加的通知可以不用停留太久 特别是 感谢吾皇 这种，手机有点挡视野。我们心里都感谢吾皇。✔
希望可以和注册高度绑定 注册的账号自动添加记录 这个有点难 如果是监听容器也没必要 我也没想好什么模式 ❌不太会哈哈哈
目前好像不支持潘多拉内置的账号密码模式(0额度消耗自动续期) 建议是只输入了账号密码的时候启用。而不是输入就提交拿Accesstoken，直接不检测账号密码的合理度用账号&密码写法。 ✔
检测到没权限 或者容器名不对 就取消右上角的菜单 或者灰色 ❌ 感觉太麻烦

**Comment by Yanyutin753** [comment]
不是可以换license 就是换了一样会超过余额的 就是他的余额是算ip的余额 本来我用了500，换了之后也是500，数据会迁移的

**Comment by Yanyutin753** [comment]
有一个开启gpts分享账号密码项 （这个gpts是分享啥 我没用过🥹 我开了那个打码的 这个是啥意思）

手机端我这边看上面还非常空 可能你没明白我的意思 我是说只需要加一个菜单 ，菜单里面放这些 这样逻辑比较清晰.（加个菜单嘛 可以试试）

**Comment by Yanyutin753** [comment]
打码那些我都放到pandora的设置上面了，新版都更新了哈哈哈哈哈

**Comment by Yanyutin753** [comment]
我不太会用 所以默认都是false，需要的话打开就行

**Comment by Yanyutin753** [comment]
搞个跳转pandoraNext web的网址
在搞个tool里面自动输出pandoraNext的调用地址嘛，就是太多人用反代或者cf，域名这些还需要自定义，到时候可以弄一个提示，调试api的话 那就难了 慢慢来 边学边写吧

**Comment by Yanyutin753** [comment]
我直接做测试 就不用调式了

**Comment by Yanyutin753** [comment]
看看更新0.5.1有啥要改进的地方

**Comment by Yanyutin753** [comment]
我好像懂了 弄一个手机验证pandoraNext的接口测试网站？

**Comment by Yanyutin753** [comment]
前端不会写啊 去github找个项目看看
哈哈哈哈哈哈哈 直接缝合怪

**Comment by Yanyutin753** [comment]
把测试集合到了跳转web链接里面，那个tokensTool帮助手册可以在线测试哈哈哈哈，用的apifox
