### ISSUE TITLE
请教部署问题

### ISSUE THREAD

**Issue by kenneth-mid** [Yanyutin753/PandoraNext-TokensTool#62]
可以单独只部署tokenstool吗？ 
通过查看介绍信息转了几层找到了你的docker部署内容，但是我想不走docker的方式，直接运行可以吗？
因为我现在还没部署，所以不是很了解你的程序运行机制和要求。如果可行我想不用docker的方式运行，如果没办法我再用docker。
谢谢你的作品，点赞

**Comment by Yanyutin753** [comment]
可以啊，但是你要先部署pandoraNext才行，然后把tokensTool的jar包放到你的pandoraNext关联的config.json文件目录下，就行
