### ISSUE TITLE
pandoara_Ip 环境变量我觉得可以取消

### ISSUE THREAD

**Issue by fightroad** [Yanyutin753/PandoraNext-TokensTool#66]
这个变量目前看好像只在重载padora服务的时候 作为访问地址使用。完全可以直接使用获取token 的服务地址。保留很容易引起误解。我一直以为是tokentools的监听ip  直到使用重载功能 发现日子里用的是这个ip拼接的重载api地址。

**Comment by Yanyutin753** [comment]
是啊 但是历史遗留问题，一键部署的改不了，不然就得都去文件里面改，要是不要要这个变量的话



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fightroad ***@***.***&gt;
发送时间: 2023年12月21日 13:17
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] pandoara_Ip 环境变量我觉得可以取消 (Issue #66)





 
这个变量目前看好像只在重载padora服务的时候 作为访问地址使用。完全可以直接使用获取token 的服务地址。保留很容易引起误解。我一直以为是tokentools的监听ip  直到使用重载功能 发现日子里用的是这个ip拼接的重载api地址。
