### ISSUE TITLE
大哥可以添加获取sess key的功能吗？

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#67]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/30854760/c41a1efb-2855-44bd-a1f4-cd7367b5ddf4)
期待新功能

**Comment by Yanyutin753** [comment]
这个过期的快 且消耗余额多 进群有exe直接拿sess

**Comment by Yanyutin753** [comment]
tool可能不会接入这个功能 群里面有个更好的exe 直接刷新

**Comment by taurusduan** [comment]
> 工具可能无法访问这个功能并且里面有一个更好的exe直接刷新

大哥群号是多少啊
