### ISSUE TITLE
能否加上oneapi提交创建channel的相关参数表单填写

### ISSUE THREAD

**Issue by xingfeng7788** [Yanyutin753/PandoraNext-TokensTool#68]
大佬能否加上oneapi提交创建channel的相关参数表单填写，比如groups group models 等等参数 您现在代码应该是配置死的

**Comment by Yanyutin753** [comment]
这个我现在实现了models 分组那些还未考虑

**Comment by Yanyutin753** [comment]
我不太清楚oneapi的分组是否是自定义还是啥

**Comment by Yanyutin753** [comment]
pandoranext的模型只有3和4的区别 现在docker已经更新更改模型了
