### ISSUE TITLE
【求助】0.5.4升级后无法重启pandoranext。

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#69]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/30854760/2ba37f58-c077-4818-9493-d1d3355ce63e)

pandoranext是0.6.1
其他的没有修改过，就单纯的定时更新：cd /tokenTools-sh && sudo sh update.sh

**Comment by Yanyutin753** [comment]
你在更新试试

**Comment by Yanyutin753** [comment]
还真是 我找找原因

**Comment by Yanyutin753** [comment]
我换了镜像源，没有在镜像里面内置docker，可能需要在docker-compose.yml添加一下这个![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/132346501/ed52a7d4-138c-4ca0-923a-2031531220f0)

**Comment by Yanyutin753** [comment]
添加完这个之后，运行这个就可以了cd /tokenTools-sh && sudo sh update.sh

**Comment by taurusduan** [comment]
> 添加完这个之后，运行这个就可以了
> 
> ```
> cd /tokenTools-sh && sudo sh update.sh
> ```

不错，完美解决
