### ISSUE TITLE
【建议】update.sh加入删除旧镜像，防止旧镜像占用过多空间

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#70]
#!/bin/bash

echo "检查 /pandora 路径是否存在"
if [ -d "/pandora" ]; then
    echo "开始更新 Pandora 服务..."

    # 切换到 /pandora 目录
    cd /pandora

    # 停止并移除所有正在运行的容器
    docker-compose down

    # 拉取最新的镜像
    docker-compose pull

    # 重新构建并启动所有服务
    docker-compose up -d --build

    echo "更新完成。"
else
    echo "没有 /pandora 路径，请先一键部署之后才能一键更新。"
fi

# 删除本地旧镜像
images=$(docker images --format "{{.ID}} {{.Repository}}" | grep PandoraNext)
images=$(docker images --format "{{.ID}} {{.Repository}}" | grep tokensTool)

# 将镜像 ID 和名称放入数组中
IFS=$'\n' read -rd '' -a image_array <<<"$images"

# 遍历数组并删除所有旧的镜像
for ((i=1; i<${#image_array[@]}; i++))
do
    image=${image_array[$i]}
    image_id=${image%% *}
    docker rmi $image_id
done

===============================
chatgpt教授的，不知道对不对。感觉设置了定时更新后还是很实用。

**Comment by taurusduan** [comment]
#!/bin/bash

echo "检查 /pandora 路径是否存在"
if [ -d "/pandora" ]; then
    echo "开始更新 Pandora 服务..."

    # 切换到 /pandora 目录
    cd /pandora

    # 停止并移除所有正在运行的容器
    docker-compose down

    # 拉取最新的镜像
    docker-compose pull

    # 重新构建并启动所有服务
    docker-compose up -d --build

    echo "更新完成。"
else
    echo "没有 /pandora 路径，请先一键部署之后才能一键更新。"
fi

images=$(docker images --format "{{.ID}} {{.Repository}}" | grep PandoraNext)
images=$(docker images --format "{{.ID}} {{.Repository}}" | grep tokensTool)

IFS=$'\n' read -rd '' -a image_array <<<"$images"

for ((i=1; i<${#image_array[@]}; i++))
do
    image=${image_array[$i]}
    image_id=${image%% *}
    docker rmi $image_id
done

**Comment by Yanyutin753** [comment]
好 晚一点改

**Comment by Yanyutin753** [comment]
这个可以自动更新嘛 要是可以自动更新就很不错

**Comment by Yanyutin753** [comment]
已更新，支持自动删除之前的旧镜像
#!/bin/bash

echo "检查 /pandora 路径是否存在"
if [ -d "/pandora" ]; then
    echo "开始更新 Pandora 服务..."

    # 切换到 /pandora 目录
    cd /pandora

    # 停止 tokensTool 和 PandoraNext 服务
    docker stop tokensTool PandoraNext

    # 移除 tokensTool 和 PandoraNext 服务
    docker rm -f tokensTool PandoraNext

    echo 拉取最新的镜像
    docker-compose pull

    # 重新构建并启动所有服务
    docker-compose up -d --build
    
    running_images=$(docker ps --format "{{.Image}}")
    
    # 获取名为PandoraNext和tokensTool的所有镜像
    images=$(docker images --format "{{.ID}} {{.Repository}}" | grep -E 'PandoraNext|tokensTool')
    
    # 初始化一个变量来跟踪是否所有的镜像都被成功删除
    all_images_removed=true
    
    # 遍历所有的镜像
    while IFS= read -r image; do
        # 提取镜像ID
        image_id=${image%% *}
    
        # 检查这个镜像是否正在运行
        if ! grep -q "$image_id" <<<"$running_images"; then
            # 如果这个镜像没有正在运行，那么删除它
            docker rmi "$image_id"
            
            # 如果删除镜像的命令失败，那么设置 all_images_removed 为 false
            if [ $? -ne 0 ]; then
                all_images_removed=false
            fi
        fi
    done <<<"$images"


    # 等待所有的后台任务都完成
    wait

    # 如果所有的镜像都被成功删除，那么输出 "所有镜像删除成功"
    if $all_images_removed; then
        echo "旧镜像删除成功。"
    else
        echo "旧镜像没有被成功删除。"
    fi
else
    echo "没有 /pandora 路径，请先一键部署之后才能一键更新。"
fi

**Comment by Yanyutin753** [comment]
直接运行
```
## 更新update.sh或者install.sh
sudo rm -rf /tokenTools-sh && cd / && git clone https://gitee.com/yangyangEN/tokenTools-sh.git
```
