### ISSUE TITLE
【请教】刚才更新后试用了一下新功能refresh_token，配合刷新机。

### ISSUE THREAD

**Issue by taurusduan** [Yanyutin753/PandoraNext-TokensTool#71]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/30854760/6510ca8b-8730-490b-ba67-3b082d424784)

大哥，咨询一下获得的refresh_token，不能直接使用刷新sess key吗？

**Comment by Yanyutin753** [comment]
这个不是一个东西 要用sess-key刷新
