### ISSUE TITLE
PandoraNext的公网访问地址和proxy模式URL的区别

### ISSUE THREAD

**Issue by fightroad** [Yanyutin753/PandoraNext-TokensTool#74]
这两个地址有什么区别吗？现在有点地方调pandora服务用PandoraNext的公网访问地址。有的地方用设置的proxy模式URL。我觉得可以统一起来。精简配置项。

**Comment by Yanyutin753** [comment]
有区别的，由于很多是default，不用填的，才加一个这个出来
