### ISSUE TITLE
基础知识

### ISSUE THREAD

**Issue by yangtongxi** [Yanyutin753/PandoraNext-TokensTool#75]
求教大佬，这几个token各是指什么，新手很懵逼
share_token
pool_token
access_token
session_token
refresh_token

**Comment by Yanyutin753** [comment]
看看fakeopen.org

**Comment by Yanyutin753** [comment]
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/132346501/dc16da49-9d34-4ab0-b1de-94d516f82058)
