### ISSUE TITLE
不能白嫖GPT4吧

### ISSUE THREAD

**Issue by alexyang-sea** [Yanyutin753/PandoraNext-TokensTool#76]
看着步骤也比较复杂，始终没找到有白嫖GPT4的办法。

**Comment by Yanyutin753** [comment]
用copilot公车就能用啊 而且群有时候会发ghu出来，直接用就行

**Comment by Yanyutin753** [comment]
哪里复杂了，直接用url加密钥就行 密钥群里面有时候会发，公车ccu，ghu也可以跑跑
