### ISSUE TITLE
有无docker方案

### ISSUE THREAD

**Issue by YoYulyvW** [Yanyutin753/PandoraNext-TokensTool#9]
群晖用，封装个docker启用方便一点

**Comment by Yanyutin753** [comment]
我现在在添加路径，但是不知道为啥 我启动包的时候 要是指定路径进去发生指令，指令只生效两次，之后就程序自动退出了，很是纳闷！代码无非是自动获取路径和手动输入路径的区别，但是就是出现bug，我现在还解决不了

**Comment by renqabs** [comment]
> 我现在在添加路径，但是不知道为啥 我启动包的时候 要是指定路径进去发生指令，指令只生效两次，之后就程序自动退出了，很是纳闷！代码无非是自动获取路径和手动输入路径的区别，但是就是出现bug，我现在还解决不了

大佬，你抱脸上的README.md里的app_port没改啊，应该是8080吧

**Comment by Yanyutin753** [comment]
啥8080，没看懂 看看图

**Comment by renqabs** [comment]
> 啥8080，没看懂 看看图
抱脸上只能开放一个端口，默认是7860
![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/c9b1779b-8be3-4a48-9ea2-0ee1fcc392a9)
bu

**Comment by YoYulyvW** [comment]
> 我现在在添加路径，但是不知道为啥 我启动包的时候 要是指定路径进去发生指令，指令只生效两次，之后就程序自动退出了，很是纳闷！代码无非是自动获取路径和手动输入路径的区别，但是就是出现bug，我现在还解决不了

我起了一个 用pm2好像没啥问题

**Comment by Yanyutin753** [comment]
你看了那个传路径的参数嘛 默认取本地地址还可以用，但是取路径，改pandoranext状态 可以用两次，开了之后关，关了之后开，程序就退出了，我也找不到原因现在



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YoYulyvW ***@***.***&gt;
发送时间: 2023年11月19日 23:13
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 有无docker方案 (Issue #9)





  
我现在在添加路径，但是不知道为啥 我启动包的时候 要是指定路径进去发生指令，指令只生效两次，之后就程序自动退出了，很是纳闷！代码无非是自动获取路径和手动输入路径的区别，但是就是出现bug，我现在还解决不了
  
我起了一个 用pm2好像没啥问题

**Comment by Yanyutin753** [comment]
> > 啥8080，没看懂 看看图
> 
> 抱脸上只能开放一个端口，默认是7860
> 
> ![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/b63cf4f7-482a-4dd5-955e-e848233e29d9)
> 
> 
> 
> ![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/e9c4d03e-733f-4823-b37b-6c9056938141)
> 
> ![image](https://github.com/Yanyutin753/PandoraNext-TokensTool/assets/130155002/872b2dfd-4757-412b-b13b-855b52d1beac)
> 
> 
> 
> 
> 
> 抱脸space docker中开启pandora的时候报错了

你搞错了 部署方式不对 你看你pandoraNext启动使用docker 的话要改环境变量的，看readme

**Comment by Yanyutin753** [comment]
docker方案太复杂了 我现在实现了改那些数据，但是更改PandoraNext的状态太难了

**Comment by YoYulyvW** [comment]
> docker方案太复杂了 我现在实现了改那些数据，但是更改PandoraNext的状态太难了

如果 PandoraNext是docker默认，那么给docker 权限黑tool 就可以容器内部执行操作docker权限了，如果是二进制，那么直接在tool容器执行就行了

**Comment by Yanyutin753** [comment]
docker没怎么学，有两种方案，用软件包部署PandoraNext我是传路径进去映射关PandoraNext 但是内部容器我刚刚试了好像弄不了，然后要是docker部署PandoraNext，就需要关掉相应的容器名，两者都实现了读取文件值，改文件值，就是现在还改不了状态，大佬，你去看看，交流一下，我下午得上课了😭，加个v吧

**Comment by Yanyutin753** [comment]
docker没怎么学，有两种方案，用软件包部署PandoraNext我是传路径进去映射关PandoraNext 但是内部容器我刚刚试了好像弄不了，然后要是docker部署PandoraNext，就需要关掉相应的容器名，两者都实现了读取文件值，改文件值，就是现在还改不了状态，大佬，你去看看，交流一下，我下午得上课了😭，加个v：15976093511

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: YoYulyvW ***@***.***&gt;
发送时间: 2023年11月20日 12:33
收件人: Yanyutin753/PandoraNext-TokensTool ***@***.***&gt;
抄送: Clivia ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [Yanyutin753/PandoraNext-TokensTool] 有无docker方案 (Issue #9)





  
docker方案太复杂了 我现在实现了改那些数据，但是更改PandoraNext的状态太难了
  
如果 PandoraNext是docker默认，那么给docker 权限黑tool 就可以容器内部执行操作docker权限了，如果是二进制，那么直接在tool容器执行就行了

**Comment by Yanyutin753** [comment]
经过gpt的努力，写出来了docker的版本😭
